project:
  type: website

website:
  title: "Ocean Health"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - coralbleaching.qmd
      - chemical.qmd
      - fishpop.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

